name: Release

on:
  release:
    types: [published]
    branches: [ master ]

permissions:
  contents: write

jobs:

  build_assets:

    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        chmod +x build.sh
        VERSION=`echo ${{ github.ref }} | awk -F/ '{print $3}'`
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        ./build.sh $VERSION

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: startsWith(github.ref, 'refs/tags/')

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: startsWith(github.ref, 'refs/tags/')

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        context: .
        push: true
        tags: |
          zhangsean/cloud189:latest,
          zhangsean/cloud189:${{ env.VERSION }}

    - name: Upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          cloud189-${{ env.VERSION }}-darwin-macos-amd64.zip
          cloud189-${{ env.VERSION }}-freebsd-386.zip
          cloud189-${{ env.VERSION }}-freebsd-amd64.zip
          cloud189-${{ env.VERSION }}-linux-386.zip
          cloud189-${{ env.VERSION }}-linux-amd64.zip
          cloud189-${{ env.VERSION }}-linux-arm64.zip
          cloud189-${{ env.VERSION }}-linux-armv7.zip
          cloud189-${{ env.VERSION }}-linux-mips.zip
          cloud189-${{ env.VERSION }}-linux-mips64.zip
          cloud189-${{ env.VERSION }}-windows-arm.zip
          cloud189-${{ env.VERSION }}-windows-x64.zip
          cloud189-${{ env.VERSION }}-windows-x86.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
